Normal:
  Names:
  -
  -
  -
  MinEfficiency:
  MaxEfficiency:
  MinFortune:
  MaxFortune:
  MinUnbreaking:
  MaxUnbreaking:
  MinExtraDrops:
  MaxExtraDrops:
  MinAcient:
  MaxAcient:
  MinSpeed:
  MaxSpeed:
  MinEnchants:
  MaxEnchants:
Rare:
  Names:
  -
  -
  -
  MinEfficiency:
  MaxEfficiency:
  MinFortune:
  MaxFortune:
  MinUnbreaking:
  MaxUnbreaking:
  MinExtraDrops:
  MaxExtraDrops:
  MinAcient:
  MaxAcient:
  MinSpeed:
  MaxSpeed:
  MinEnchants:
  MaxEnchants:
Epic:
  Names:
  -
  -
  -
  MinEfficiency:
  MaxEfficiency:
  MinFortune:
  MaxFortune:
  MinUnbreaking:
  MaxUnbreaking:
  MinExtraDrops:
  MaxExtraDrops:
  MinAcient:
  MaxAcient:
  MinSpeed:
  MaxSpeed:
  MinEnchants:
  MaxEnchants:
Ultra:
  Names:
  -
  -
  -
  MinEfficiency:
  MaxEfficiency:
  MinFortune:
  MaxFortune:
  MinUnbreaking:
  MaxUnbreaking:
  MinExtraDrops:
  MaxExtraDrops:
  MinAcient:
  MaxAcient:
  MinSpeed:
  MaxSpeed:
  MinEnchants:
  MaxEnchants:

